file=open("stud.txt","w")
file.write("101,john,85\n")
file.write("102,Emma,90\n")
print("File created and data written")
file=open("stud.txt","r")
data=file.read()
print("student Records:")
print(data)
file=open("stud.txt","a")
file.write("103,Liam,88\n")
file.close()
print("Data appended successfully")